wandb:
  project: placeholder
  entity: placeholder
  name: placeholder
  mode: online
  id: null

output_dir: outputs
seed: 3407

diffusion:
  pretrained_model_name_or_path: "stabilityai/stable-video-diffusion-img2vid-xt"
  pretrain_unet: "Yuyang-z/genxd"
  unet_config: "models/unet_cascade_4d_motion.json"
  per_gpu_batch_size: 1
  gradient_accumulation_steps: 1
  num_frames: 12
  gradient_checkpointing: true
  use_8bit_adam: true
  max_train_steps: 300000
  width: 256
  height: 256
  checkpointing_steps: 2000
  checkpoints_total_limit: 1000
  learning_rate: 2.0e-5
  lr_warmup_steps: 2000
  seed: ${seed}
  mixed_precision: "fp16"
  validation_steps: 1000
  num_validation_images: 5
  output_dir: "outputs-svd"
  use_motion_embedding: true
  single_view_ratio: 0.5


evaluator:
  loss:
    lambda_lpips: 0.1
  optim:
    position_lr_init: 0.00016
  max_iterations: 200